### ISSUE TITLE
Use case: Put document

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/HelseAPI#7]
Skrive et dokument til journalsystem via FHIR API.

Samme metode bør kunne virke for både SMART on FHIR til EPJ, og eksternt, f.eks. fra VKP til (kommunal) EPJ. 

Et dokument kan være
- Binært, f.eks. en PDF
- Strukturert, f.eks. FHIR Document/composition, f.eks. et enkelt notat
- Vedlagt, eller referert til (DocumentReference). 

Noen kilder:
MedMij: https://informatiestandaarden.nictiz.nl/wiki/MedMij:V2018.02_FHIR_PDFA
IHE MHD: https://wiki.ihe.net/index.php/Mobile_access_to_Health_Documents_(MHD)
Cerner: https://fhir.cerner.com/millennium/dstu2/infrastructure/document-reference/

**Comment by rockphotog** [comment]
Litt av behovet for DocumentReference selv om man bruker Composition (og refererer til en Binary):

> Unlike CDA, the context defined in the Composition (the confidentiality, subject, author, event, event period and encounter) **apply to the composition** and do not specifically apply to the resources referenced from the section.entry. There is no context flow model in FHIR, so each resource referenced from within a Composition expresses its own individual context. In this way, clinical content can safely be extracted from the composition.

(min utheving)

Kilde: https://www.hl7.org/fhir/composition.html

**Comment by kennethmyhra** [comment]
Eksempel på en Transaction med to dokumenter, ett tekstdokument og ett binært PDF-dokument.

Eksemplene benytter Loinc-koder

Bundle inneholder:
* to Binary-ressurser:
  * Binary-ressurs `B0B56521-7FC5-4F15-ABE0-3AEC42FF240C` inneholder tekstdokumentet i base64-encoded format
  * Binary-ressurs `CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A` inneholder PDF-dokumentet i base64-encoded format
* to DocumentReference ressurser:
  * Konklusjon (tekstdokumentet):
    * `content` refererer til Binary-ressursen `B0B56521-7FC5-4F15-ABE0-3AEC42FF240C`
    * `type.coding` = Loinc-verdien `51848-0 - Assessment note`
    * `type.text` tekstlig representasjon av type.coding `Assessment note`
    * `subject` referanse til pasient
    * `author` referanse til fastlege
    * `authenticator` referanse til fastlege (usikker på om vi skal bruke denne?)
    * `encounter` referanse til konsultasjon
  * Kopi av helseattest (PDF-dokumentet):
    * `content` refererer til Binary-ressursen `CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A`
    * `type.coding` = Loinc-verdien `74465-6 - Questionnaire response Document`
    * `type.text` tekstlig representasjon av type.coding `Questionnaire response Document`
    * `subject` referanse til pasient
    * `author` referanse til fastlege
    * `authenticator` referanse til fastlege (usikker på om vi skal bruke denne?)
    * `encounter` referanse til konsultasjon

```json
{
  "resourceType": "Bundle",
  "id": "urn:uuid:0138f9b0731c4c518aa19ea85bd4807a",
  "type": "transaction",
  "entry": [
    {
      "fullUrl": "urn:uuid:B0B56521-7FC5-4F15-ABE0-3AEC42FF240C",
      "resource": {
        "resourceType": "Binary",
        "contentType": "text/plain",
        "securityContext": {
          "reference": "urn:uuid:B0B56521-7FC5-4F15-ABE0-3AEC42FF240D"
        },
        "data": "UVhWMGIyZGxibVZ5WlhKMElHdHZibXRzZFhOcWIyNGdLeUJzWldkbGJuTWdaV2R1WlNCdWIzUmhkR1Z5"
      },
      "request": {
        "method": "POST",
        "url": "Binary"
      }
    },
    {
      "fullUrl": "urn:uuid:B0B56521-7FC5-4F15-ABE0-3AEC42FF240D",
      "resource": {
        "resourceType": "DocumentReference",
        "status": "current",
        "docStatus": "final",
        "type": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "51848-0",
              "display": "Assessment note"
            }
          ],
          "text": "Assessment note"
        },
        "subject": {
          "reference": "Patient/123"
        },
        "date": "2019-11-25T08:25:18.406722+00:00",
        "author": [
          {
            "reference": "Practitioner/456"
          }
        ],
        "authenticator": {
          "reference": "Practitioner/456"
        },
        "content": [
          {
            "attachment": {
              "contentType": "text/plain",
              "url": "urn:uuid:B0B56521-7FC5-4F15-ABE0-3AEC42FF240C"
            }
          }
        ],
        "context": {
          "encounter": [
            {
              "reference": "Encounter/789"
            }
          ]
        }
      },
      "request": {
        "method": "POST",
        "url": "DocumentReference"
      }
    },
    {
      "fullUrl": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A",
      "resource": {
        "resourceType": "Binary",
        "contentType": "application/pdf",
        "securityContext": {
          "reference": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17B"
        },
        "data": "SlZCRVJp(snipped for brevity)"
      },
      "request": {
        "method": "POST",
        "url": "Binary"
      }
    },
    {
      "fullUrl": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17B",
      "resource": {
        "resourceType": "DocumentReference",
        "status": "current",
        "docStatus": "final",
        "type": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "74465-6",
              "display": "Questionnaire response Document"
            }
          ],
          "text": "Questionnaire response Document"
        },
        "subject": {
          "reference": "Patient/123"
        },
        "date": "2019-11-25T08:25:18.4113618+00:00",
        "author": [
          {
            "reference": "Practitioner/456"
          }
        ],
        "authenticator": {
          "reference": "Practitioner/456"
        },
        "content": [
          {
            "attachment": {
              "contentType": "application/pdf",
              "url": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A"
            }
          }
        ],
        "context": {
          "encounter": [
            {
              "reference": "Encounter/789"
            }
          ]
        }
      },
      "request": {
        "method": "POST",
        "url": "DocumentReference"
      }
    }
  ]
}
```

**Comment by rockphotog** [comment]
Bli med i diskusjonen @jornsikkerbol  - du hadde et godt argument for å bruke composition.

**Comment by kennethmyhra** [comment]
Eksempel på en `Bundle` av type `document` med en composition som inneholder en tekstseksjon + ett dokument som er type PDF-dokument.

Bundle inneholder:
* En Composition-ressurs:
  * En samling av notater og dokumenter i en gitt kontekst samlet i en komposisjon
    * `encounter` referanse til konsultasjon
    * `title` tittel som omfatter de samlede notatene og dokumentene (komposisjonen)
    * Eksempel på en seksjon som inneholder tekst:
      * `title` tittelen på seksjonen
      * `code.coding[x]` = Loinc-verdien `51848-0 - Assessment note`
      * `code.text` = tekstlig representasjon av code.coding `Assessment note`
      * `text` den faktiske teksten, konklusjon + ev. legens notater
    * Eksempel på en seksjon som referer ett dokument:
      * `title` tittelen på seksjonen
      * `code.coding` = Loinc-verdien `47420-5 - Functional status assessment note`
      * `code.text` = tekstlig representasjon av code.coding `Functional status assessment note`
      * `entry` referanse til DocumentReference med id `CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17B`
* en Binary-ressurs:
  * Binary-ressurs `CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A` inneholder PDF-dokumentet i base64-encoded format
* en DocumentReference-ressurs:
  * Kopi av helseattest (PDF-dokumentet):
    * `content` refererer til Binary-ressursen `CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A`
    * `status`: `current`
    * `docStatus`: `final`
    * `type.coding` = Loinc-verdien `74465-6 - Questionnaire response Document`
    * `type.text` tekstlig representasjon av type.coding `Questionnaire response Document`
    * `subject` referanse til pasient
    * `author` referanse til fastlege
    * `authenticator` referanse til fastlege (usikker på om vi skal bruke denne?)
    * `encounter` referanse til konsultasjon

```json
{
  "resourceType": "Bundle",
  "id": "urn:uuid:a5b6620bfe6c4dac985a11bc8de7ad91",
  "type": "document",
  "entry": [
    {
      "fullUrl": "urn:uuid:e1a0cac09f784f7688241c7f6b3ea035",
      "resource": {
        "resourceType": "Composition",
        "encounter": {
          "reference": "Encounter/123"
        },
        "title": "Helseattest førerkort",
        "section": [
          {
            "title": "Konklusjon/notat",
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "51848-0",
                  "display": "Assessment note"
                }
              ],
              "text": "Assessment note"
            },
            "text": {
              "div": "Autogenerert konklusjon + legens egne notater"
            }
          },
          {
            "title": "Helseattest inkl. konklusjon",
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "47420-5",
                  "display": "Functional status assessment note"
                }
              ],
              "text": "Functional status assessment note"
            },
            "entry": [
              {
                "reference": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17B"
              }
            ]
          }
        ]
      }
    },
    {
      "fullUrl": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A",
      "resource": {
        "resourceType": "Binary",
        "contentType": "application/pdf",
        "securityContext": {
          "reference": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17B"
        },
        "data": "SlZCRV(snipped for brevity)"
      }
    },
    {
      "fullUrl": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17B",
      "resource": {
        "resourceType": "DocumentReference",
        "status": "current",
        "docStatus": "final",
        "type": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "74465-6",
              "display": "Questionnaire response Document"
            }
          ],
          "text": "Questionnaire response Document"
        },
        "subject": {
          "reference": "Patient/123"
        },
        "date": "2019-11-25T08:25:21.3294991+00:00",
        "author": [
          {
            "reference": "Practitioner/456"
          }
        ],
        "authenticator": {
          "reference": "Practitioner/456"
        },
        "content": [
          {
            "attachment": {
              "contentType": "application/pdf",
              "url": "urn:uuid:CB2ADB6F-06B0-458A-AA37-2B8B7CE4E17A"
            }
          }
        ]
      }
    }
  ]
}
```

**Comment by kennethmyhra** [comment]
@rockphotog @jornsikkerbol eksempel med Composition

**Comment by kennethmyhra** [comment]
@rockphotog så først kommentaren din over nå

>the context defined in the Composition (the confidentiality, subject, author, event, event period and encounter) apply to the composition and do not specifically apply to the resources referenced from the section.entry.

Dette er et godt poeng.
`Composition` er en komposisjon av ressurser (på ett eller annet tidspunkt) uavhengig av når de refererte ressursene ble opprettet eller hvem de igjen referer.

>There is no context flow model in FHIR, so each resource referenced from within a Composition expresses its own individual context.

De refererte ressursene må uansett referere til subjekt, konsultasjon osv. uavhengig av `Composition`

**Comment by rockphotog** [comment]
Lloyd McKenzie "endorser" å putte base64-vedlegger rett i DocumentReference - ikke behov for Binary overhodet?

https://chat.fhir.org/#narrow/stream/179270-fhir.2Fdocuments/topic/Clinical.20Notes/near/174114877

**Comment by kennethmyhra** [comment]
Utsagnet kommer litt ut av det blå, jeg ser spørsmålet

> Does this mean that an endorsed way to exchange a clinical note in FHIR is to use a DocumentReference resource with the content of the note as base 64 binary in DocumentReference.content.attachment.data?

Ser deretter LLoyd bekrefter med Yes, men hvor denne endorsement opprinnelig kommer fra klarer jeg ikke finne.

Gikk gjennom lenkede dokumenter og CR som var lenket til [FHIR-14720](https://jira.hl7.org/browse/FHIR-14720), men finner fortsatt ikke opprinnelig endorsement. Ser også at det ikke er enighet om FHIR-14720, men lite informasjon om hva som ble diskutert.

Er det noe jeg ikke får med meg?

**Comment by kennethmyhra** [comment]
@rockphotog Kan du ta en titt på guiden + kodeverkene som benyttes her: http://hl7.org/fhir/us/core/2019Jan/clinical-notes-guidance.html

Kodene jeg tenker er av umiddelbar interesse er:
* [34117-2 History and physical note](https://loinc.org/34117-2.html/) for helseattesten
* [11488-4 Consult note](https://loinc.org/11488-4.html/) for journalnotat (løpende?)

**Comment by kennethmyhra** [comment]
https://chat.fhir.org/#narrow/stream/179270-fhir.2Fdocuments/topic/Clinical.20Notes/near/186882047

* Stilt spørsmål om hvor denne "endorsement" er dokumentert
* Også stilt spørsmål om hva definisjonen av "note" er. Jeg kan forstå at dette forenkler tekstnotater og det virker som en lur måte å gjøre det på, men det forenkler ikke binære dokumenter.
